version: '3'
services:
  laravel.test:
    build:
      context: ./docker/8.1
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.1/app
    ports:
      - '${APP_PORT:-80}:80'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    # depends_on:
    #   - mysql
    #   - redis
    # mysql:
    #   image: 'mariadb:latest'
    #   ports:
    #     - '${FORWARD_DB_PORT:-3306}:3306'
    #   environment:
    #     MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    #     MYSQL_DATABASE: '${DB_DATABASE}'
    #     MYSQL_USER: '${DB_USERNAME}'
    #     MYSQL_PASSWORD: '${DB_PASSWORD}'
    #     MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    #   volumes:
    #     - './data/db/:/var/lib/mysql'
    #   networks:
    #     - sail
    #   healthcheck:
    #     test: [ "CMD", "mysqladmin", "ping" ]
    # redis:
    #   image: 'redis:alpine'
    #   ports:
    #     - '${FORWARD_REDIS_PORT:-6379}:6379'
    #   volumes:
    #     - './data/redis/:/data'
    #   networks:
    #     - sail
    #   healthcheck:
    #     test: [ "CMD", "redis-cli", "ping" ]
networks:
  sail:
    driver: bridge
volumes:
  sailredis:
    driver: local
